version: '3.4'

x-app-variables: &app-variables
  DJANGO_SETTINGS_MODULE: lolmd.settings.dev
  SECRET_KEY: ${SECRET_KEY:-Keep_it_secret,_keep_it_safe}
  RIOT_API_KEY: ${RIOT_API_KEY}
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_NAME: lolmd
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  HEARTBEAT_RATE: 60
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_PASSWORD: ${REDIS_PASSWORD:-redis}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD:-creme}

services:

  postgres:
    restart: always
    image: postgres:11.3
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=lolmd
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - PGDATA=/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis:4.0.11
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
    ports:
      - "6379:6379"

  app:
    restart: always
    build: .
    environment: *app-variables
    command: >
      bash -c "python manage.py makemigrations core
      && python manage.py migrate --noinput
      && python manage.py flush --noinput
      && python manage.py flush_redis
      && python manage.py add_regions
      && python manage.py add_models
      && python manage.py add_admins
      && python manage.py queue_random_matches
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  rqworker:
    restart: always
    build: ./
    environment: *app-variables
    command: bash wait-for-it.sh app:8000 -t 0 -- python manage.py rqworker default
    volumes:
      - .:/code
    depends_on:
      - app

  rqscheduler:
    restart: always
    build: ./
    environment: *app-variables
    command: bash wait-for-it.sh app:8000 -t 0 -- python manage.py rqscheduler --interval 60
    volumes:
      - .:/code
    depends_on:
      - app

  redis-commander:
    restart: always
    image: rediscommander/redis-commander
    ports:
      - "8082:8082"
    links:
      - redis:redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - PORT=8082
    depends_on:
      - redis
